# Generated by Django 5.2.6 on 2025-09-23 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog title or target keyword', max_length=500)),
                ('primary_keywords', models.TextField(help_text='Primary keywords (comma-separated)')),
                ('num_competitors', models.IntegerField(default=3, help_text='Number of competitors to analyze')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_content', models.TextField(blank=True, help_text='Generated blog content', null=True)),
                ('formatted_post', models.TextField(blank=True, help_text='Formatted blog post', null=True)),
                ('word_count', models.CharField(blank=True, max_length=50, null=True)),
                ('competitor_analysis', models.JSONField(blank=True, null=True)),
                ('blog_outline', models.JSONField(blank=True, null=True)),
                ('doc_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
