# Generated by Django 5.2.6 on 2025-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggeneration',
            name='secondary_keywords',
            field=models.TextField(blank=True, help_text='Secondary keywords (comma-separated) - Optional', null=True),
        ),
        migrations.AddField(
            model_name='bloggeneration',
            name='target_length',
            field=models.CharField(blank=True, help_text='Target blog length - Optional', max_length=20, null=True),
        ),
    ]
