# Generated by Django 5.2.6 on 2025-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_automation', '0002_bloggeneration_secondary_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggeneration',
            name='blog_analysis_data',
            field=models.JSONField(blank=True, help_text='Generated blog analysis and outline data', null=True),
        ),
        migrations.AlterField(
            model_name='bloggeneration',
            name='blog_outline',
            field=models.TextField(blank=True, help_text='Custom blog outline/structure - Optional', null=True),
        ),
    ]
