# Generated by Django 5.2.6 on 2025-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_automation', '0003_bloggeneration_blog_analysis_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggeneration',
            name='primary_keywords',
            field=models.TextField(blank=True, help_text='Primary keywords (comma-separated) - Optional', null=True),
        ),
    ]
