# Generated by Django 5.2.6 on 2025-10-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_automation', '0004_alter_bloggeneration_primary_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggeneration',
            name='html_format',
            field=models.BooleanField(default=False, help_text='Generate content in HTML markup format with embedded links'),
        ),
    ]
