# Generated by Django 5.2.6 on 2025-10-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_automation', '0005_bloggeneration_html_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggeneration',
            name='html_format',
        ),
    ]
